export const FILE_TYPE_MAP = {
    //代码
    js: 'code',
    c: 'code',
    java: 'code',
    php: 'code',
    css: 'code',
    // html: 'code',
    vue: 'code',
    jsx: 'code',
    ts: 'code',
    //图片
    bmp: 'picture',
    jpeg: 'picture',
    png: 'picture',
    jpg: 'picture',
    gif: 'picture',
    heic: 'picture',
    //视频
    rmvb: 'video',
    avi: 'video',
    rm: 'video',
    mov: 'video',
    wmv: 'video',
    mp4: 'video',
    '3gp': 'video',
    //音乐
    wav: 'music',
    mp3: 'music',
    wma: 'music',
    amr: 'music',
    aac: 'music',
    flac: 'music',
    ape: 'music',
    //应用
    exe: 'appication',
    dmg: 'appication',
    apk: 'appication',
    ipa: 'appication',
    //文档
    txt: 'document',
    rtf: 'document',
    log: 'document',
    doc: 'document',
    docx: 'document',
    ppt: 'document',
    pptx: 'document',
    xls: 'document',
    xlsx: 'document',
    pdf: 'document',
    html: 'document',
    htm: 'document',
    //其他
    zip: 'other',
    rar: 'other',
    iso: 'other',
    tmp: 'other',
    dll: 'other',
    sys: 'other'
};
